### ISSUE TITLE
The plist file at path doesn't exist

### ISSUE THREAD

**Issue by MaxAst** [MaxAst/expo-share-extension#9]
```
> expo prebuild -p ios --clean

Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding, so you can revert the changes made by this command if necessary.

✔ Would you like to proceed? … yes

✔ Cleared ios code
✔ Created native directory
› Using current versions instead of recommended react-native@0.73.4.
✔ Updated package.json | no changes
» ios: icon: This is the image that your app uses on your home screen, you will need to configure it manually.
✔ Finished prebuild
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: An error occurred while processing the post-install hook of the Podfile.

[!] The plist file at path `/Users/maximilianast/dev/test-share-ios/ios/Info.plist` doesn't exist.


/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/xcodeproj-1.23.0/lib/xcodeproj/plist.rb:17:in `read_from_path'
/Users/maximilianast/dev/test-share-ios/node_modules/react-native/scripts/cocoapods/utils.rb:553:in `block in update_ats_in_plist'
/Users/maximilianast/dev/test-share-ios/node_modules/react-native/scripts/cocoapods/utils.rb:551:in `each'
/Users/maximilianast/dev/test-share-ios/node_modules/react-native/scripts/cocoapods/utils.rb:551:in `update_ats_in_plist'
/Users/maximilianast/dev/test-share-ios/node_modules/react-native/scripts/cocoapods/utils.rb:575:in `apply_ats_config'
/Users/maximilianast/dev/test-share-ios/node_modules/react-native/scripts/react_native_pods.rb:310:in `react_native_post_install'
/Users/maximilianast/dev/test-share-ios/ios/Podfile:57:in `block (3 levels) in from_ruby'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:149:in `message'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:183:in `integrate'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:170:in `install!'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/Users/maximilianast/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/Users/maximilianast/.rbenv/versions/2.7.5/bin/pod:23:in `load'
/Users/maximilianast/.rbenv/versions/2.7.5/bin/pod:23:in `<main>'
```

**Comment by MaxAst** [comment]
A dev on Twitter ran into the error above. This is due to a version mismatch between the Expo SDK and React Native. You can fix this by running `npx expo install --fix`. Posting this here for visibility/GitHub search, in case other devs run into this
